language: python
python:
  - "2.7"
install:
  - pip install coveralls coverage pyyaml --use-mirrors
  - python setup.py install
# command to run tests
script: nosetests tests --with-coverage --cover-package morpheus --cover-erase
after_success: coveralls
notifications:
  email:
    - ziad@sawalha.com
